[package]
name = "twip-hardware"
version = "0.0.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio = "*"
hyper = { version = "0.14.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
